spring.application.name=meeting-scheduling-platform

server.port=16200

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/scheduler}
spring.datasource.username=${DB_USERNAME:scheduler}
spring.datasource.password=${DB_PASSWORD:scheduler}
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
